from typing import Protocol

class Provider(Protocol):
    def clean(self) -> bool:...
    def info(self, package:str) -> bool:...
    def install(self, *package:str) -> bool:...
    def list_installed(self) -> bool:...
    def remove(self, *package:str) -> bool:...
    def search(self, query:str) -> bool:...
    def stats(self) -> bool:...
    def update(self) -> bool:...
    def upgrade(self) -> bool:...