from typing import Protocol

class Provider(Protocol):
    def clean(self) -> bool:
        """remove unused packages"""
        ...
    def info(self, package:str) -> bool:
        """display information on a specific package"""
        ...
    def install(self, *package:str) -> bool:
        """install a package or series of packages"""
        ...
    def list_installed(self) -> bool:...
    def remove(self, *package:str) -> bool:...
    def search(self, query:str) -> bool:...
    def stats(self) -> bool:...
    def update(self) -> bool:...
    def upgrade(self) -> bool:...